CREATE TABLE ALBUM  ( 
						AL_ID  VARCHAR(100) NOT NULL,
						AL_NAME VARCHAR(100) NOT NULL,
						AL_ARTIST_ID VARCHAR(100) NOT NULL,
						AL_RELEASEDATE DATE NOT NULL,
						AL_POPULARITY INTEGER,
						AL_GENRE VARCHAR(50)[] 
                    );
                    
CREATE TABLE TRACKS (
						TR_ID VARCHAR(100) NOT NULL,
						TR_NAME VARCHAR(255) NOT NULL,
						TR_ARTIST_ID VARCHAR(100) NOT NULL,
						TR_ALBUM_ID VARCHAR(100),
						TR_POPULARITY INTEGER
                    );
                    
CREATE TABLE PERSON (
						P_ID VARCHAR(100) NOT NULL,
						P_NAME VARCHAR(100) NOT NULL,
						P_TYPE VARCHAR(50) NOT NULL
                    );

CREATE TABLE ARTIST (
						AR_ID VARCHAR(100) NOT NULL,
						AR_NUM_FOLLOWERS INTEGER NOT NULL,
						AR_POPULARITY INTEGER,
						AR_GENRE VARCHAR(50)[]
                    );

CREATE TABLE AUTHOR (
						AU_ID VARCHAR(100) NOT NULL,
						AU_NATIONALITY VARCHAR(50) NOT NULL
                    );


CREATE TABLE AUDIOBOOK (
						AB_ID VARCHAR(100) NOT NULL,
						AB_NAME VARCHAR(100) NOT NULL,
						AB_AUTHOR_ID VARCHAR(100) NOT NULL,
						AB_PUBLISHER VARCHAR(200) NOT NULL,
						AB_LANGUAGE VARCHAR(100)[] NOT NULL,
						AB_AVAILABLE_MARKET VARCHAR(100)[]
                            
                    );